### ISSUE TITLE
Using point cloud/depth only on own data

### ISSUE THREAD

**Issue by c-bah** [GeeeG/CloudPose#1]
Hello, very nice work you have done with this paper + implementation!

I wanted to ask you if you think this project was something I can build upon for my own purposes. I don't have any image data, however I have point clouds (or alternatively depth images) of my scene and my objects I want to detect. Furthermore, I have synthetically generated depth images (can be easily translated into point clouds) of scenes with my objects in them, where the exact poses are stored in an attached json file for each image. I want to use a neural net to get me the 6D pose of my objects in a scene.

Do you think your CloudPose would be a fit for this problem? If so, can you think of the changes I would have to make in order to get it running with the different input set?

Thanks in advance and best regards!

**Comment by GeeeG** [comment]
Hi, yes I think CloudPose could be a good candidate for your problem. For inference a pose, it needs the segmented object, plus its class label, if you have more than one object. The only thing you need to figure out is how to get this segmented point cloud, and if you have synthetic data already, then at least for training you have free segmentation information. And for testing, if you have e.g. a table top scenario you could just do plane removal and get the segment (hopefully), but this could be a bit tricky. Hope this answers some of your questions, and if you can give me more detials of your application I could try to help more! Thank you for your interest in our work and point clouds!

**Comment by c-bah** [comment]
Awesome, thank you for your answer. In the mean time I decided to go with an easier completely different approach which is, as it turns out, presumably performing a bit worse than yours. So I will definately give it a try later this year.

**Comment by GeeeG** [comment]
Sure! Let me know how it goes, I also planned to have it running in our robot lab later this year, would be good to discuss in case we run into same problems.
