### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by ZhangYi0810** [GeeeG/CloudPose#10]
hi，i can not download the train datasets from the link in README

Could you show me another way to get the  datasets?

Thank you!

**Comment by GeeeG** [comment]
Do you have further problems with downloading the data?

**Comment by ZhangYi0810** [comment]
I have got the training data。Could you give me the raw data when it doesn't convert to tfrecords? @GeeeG

**Comment by GeeeG** [comment]
The raw data you can download from https://rse-lab.cs.washington.edu/projects/posecnn/, it's around 265GB

**Comment by ZhangYi0810** [comment]
Ok,I will try it. @GeeeG
