### ISSUE TITLE
object_model_dir 

### ISSUE THREAD

**Issue by ZhangYi0810** [GeeeG/CloudPose#11]
The obj_models is on the folder object_model_tfrecord  about obj_models.tfrecords?

**Comment by GeeeG** [comment]
yes

**Comment by ZhangYi0810** [comment]
thank you,I am training it now.

**Comment by KAOeric** [comment]
@Yerless  Sorry!  Can i ask what is the  path about data_dir and object_model_dir? Could you show me

**Comment by ZhangYi0810** [comment]
The object_model_dir is 'object_model_tfrecord/obj_models.tfrecords'
The data_dir is 'ycb_video_data_tfRecords/FPS1024/' 
The folder object_model_tfrecord and ycb_video_data_tfRecords/FPS1024 already exist in the source code，you only should put the training data in 'ycb_video_data_tfRecords/FPS1024',the model data already in the          'object_model_tfrecord'@KAOeric

**Comment by KAOeric** [comment]
Thank you. I did it now.
