### ISSUE TITLE
evaluate code

### ISSUE THREAD

**Issue by qingchenkanlu** [GeeeG/CloudPose#15]
Hi, is there any code used for evaluating in the repository? If no, can you add it? Thank you!

**Comment by qingchenkanlu** [comment]
Sorry, I have found the code. I want to know how you show the pose in the video like this 
![微信截图_20211215092707](https://user-images.githubusercontent.com/44363924/146106032-e6dc3c23-0d3a-43ac-a124-dd27e5f76af9.png)

**Comment by GeeeG** [comment]
Hi, I don't have access to the matlab code for this right now, but I have some python code for this you can find: https://github.com/GeeeG/6D_pose_from_april_tag/blob/fa55d184b7fd05641cf017fa5ff26cc8a723370d/test_1.py#L60, basically you need the x,y,z coordinates of object model, the camera intrinsic parameters, and the predicted rotation&translation to do this 3D to 2D projection.

**Comment by qingchenkanlu** [comment]
OK，thanks！

**Comment by Windson9** [comment]
Hi @qingchenkanlu. Can you please point to where you were able to get the evaluation code? Thanks!
