### ISSUE TITLE
about the input point cloud

### ISSUE THREAD

**Issue by LindgeW** [GeeeG/CloudPose#16]
Hi, 

As shown in Fig 2(b), in order to estimate the 6D pose, I just wonder the point cloud (with n points) of the known object fed into the BaseNet is in the *camera coordinate* or in the *object coordinate* ?

That's to say, what coordinate system is the input point cloud in ?

Thank you.

**Comment by GeeeG** [comment]
Hi, the input to the BaseNet is the observed object points in the camera coordinate.

**Comment by LindgeW** [comment]
ok
