### ISSUE TITLE
Encoding object model to tfrecords format

### ISSUE THREAD

**Issue by gilad011** [GeeeG/CloudPose#7]
Hi @GeeeG,

I'm trying to train the network on a customized dataset.
How can I encode the object ground truth CAD models?
to a file named: obj_model.tfrecords.
I saw that it holds FixedLenFeature of [2048, 6], what is it stands for?

Didn't see any referees for that in the scripts in ycb_video_data_tfRecords.

**Comment by GeeeG** [comment]
Hi @gilad011 , I added the script for creating obj_model.tfrecords in "object_model_tfrecord". You need to convert your CAD model to ply files. I gave a download link for the ply files I used for the YCB video dataset.
2048 stands for the number of points in the object models, the script I just uploaded creates a more dense version with 4096 points, you can change this for your preference.
6 stands for xyzrgb
