### ISSUE TITLE
dataset_generator returns 'None' when tf.errors.outOfRange exception occurs

### ISSUE THREAD

**Issue by gilad011** [GeeeG/CloudPose#8]
Hi all,

I am re-implementing the code for use on another dataset.
Im at the stage of re-implementing the dataset decoding to TFrecords.

Allready managed to tune the script '1_ycb_to_tfRecords.py' and to make it work and save tfrecords sequences.
Having trouble with tunning the script '2_dataset_to_tfRecords_small.py':

In create_record function, when iterating on the generator that has been created by dataset_generator function, I thrown out of the loop in the snippet by yielding 'None' value, thus the TFRecord file is saved as empty. 
![image](https://user-images.githubusercontent.com/40541255/92743753-7f4c5700-f389-11ea-92a6-7ff5a7005697.png)

could you help in suggesting what could be wrong?

**Comment by GeeeG** [comment]
It's hard to tell what's the problem with the discrption. Could you please show me the error messages? And did the first scrpit save the tfrecords properly?

**Comment by gilad011** [comment]
Hi, the first script did save the tfrecord file properly. 

In fact, I do not get errors, the second script writes an empty tfrecords file. 

When I debug, I print values within tensorflow graph, I can track that the dataset object is containing all the data.
The first iteration of the generator ends up with OutOfRange error (occur in the end of the data), which means that no value was yielded. 
This causes the script to terminate the loop on the generator before any data was entered. I can provide more information if needed.

**Comment by gilad011** [comment]
While debugging I saw that sess.run(next_element) is actually moving through all the dataset elements, and not returning only the (single) next element of the dataset. 
is it related to tensorflow/python versions?
how can you make the iterator go through each element in dataset object?
