### ISSUE TITLE
Data can not download with the zip file

### ISSUE THREAD

**Issue by KAOeric** [GeeeG/CloudPose#9]
I can not download the zip file about  data before i want to run object_6d_pose.py 
how can i do or where else can i download the data

**Comment by ZhangYi0810** [comment]
Do you download the data yet?
If you have got it,please tell me how to download id.
Thank you!

**Comment by KAOeric** [comment]
Yes i download it. I use another network and i download in D:
This is success for me.

**Comment by ZhangYi0810** [comment]
You only use the link from the README,could you show me the way you are

**Comment by ZhangYi0810** [comment]
hi，could you show me the way you are

**Comment by GeeeG** [comment]
@Yerless do you mean the training_data.zip? Do you have permission issues? Could you please try this link: https://drive.google.com/file/d/10gvvJdllvl0mMGvpiwbZ8KEzVlJS2gyZ/view?usp=sharing

**Comment by ZhangYi0810** [comment]
Thank you!I got the training datasets. @GeeeG
